version: "3"

services:
  ecommerce:
    build: ./ecommerce
    ports:
      - "8081:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    links:
      - postgres:postgres
    env_file: ./ecommerce/.env

  postgres:
    image: postgres:latest
    ports:
      - "5490:5432"
